### ISSUE TITLE
no documentation

### ISSUE THREAD

**Issue by alexgarry** [dwf/convolupy#1]
I can do it, but I have a few questions...

**Comment by dwf** [comment]
I would strongly recommend against using this thing. It's an old experiment, and most of it works, but it'll be slow as balls.

**Comment by dwf** [comment]
Check out http://github.com/lisa-lab/pylearn2 and http://github.com/Theano/Theano for better options.

**Comment by alexgarry** [comment]
Thanks for your advice!
But I have a few questions, can I contact with you via email?

**Comment by dwf** [comment]
Go for it. I can't promise I'll reply before June 1 though.
